### ISSUE TITLE
Add visibility of exposed scope to config

### ISSUE THREAD

**Issue by anderssonw** [nais/digdirator#341]
I would like to be able to set the visibility of an exposed scope to be private, but currently it is always set to Public, without possible configurations.

Something like this would be nice:
```yaml
    exposes:
      - name: "name"
        visibility: "PRIVATE"
        enabled: true
        product: "product"
        consumers:
          - orgno: "971040238"
```
